# -*- coding: utf-8 -*-
"""python_donem_odev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11y99OHPQCdzo_ug5NiAD2qw8m49B-Mfl
"""

import random # Random Kütüphanesi

#Değişken Tanımlama
ad_soyad = "Semih Açıkgöz"   #String
aylik_ucret = 550.75         #Float
sadakat_ayi = 18             #Int
aktif_mi = True              #Bool

#Liste Kullanımı
sunulan_hizmetler = ["Fiber İnternet", "IPTV", "Sabit Telefon", "Mobil Hat", "Akıllı Ev"]

#Sözlük Kullanımı
musteri_bilgileri =  {
    "ad_soyad": ad_soyad,
    "aylik_ucret": aylik_ucret,
    "sadakat_ayi": sadakat_ayi,
    "aktif_mi": aktif_mi
}

# If-Else
# eğer aylık ücret 500'den büyükse ya da sadakat ayı 24den büyükse
if musteri_bilgileri["aylik_ucret"] > 500 or musteri_bilgileri["sadakat_ayi"] > 24:
    print("VIP Müşteri: İndirim Tanımla")
else:
    print("Standart Müşteri")

# String Operasyonları
ad_buyuk_harf = musteri_bilgileri["ad_soyad"].upper()   # upper metodu ile büyük harfe çevirme
rastgele_sayi = random.randint(1000, 9999)              # 1000-9999 arası rastgele sayı üretme
customerID = "IST-2026-" + str(rastgele_sayi)           # Tip dönüşümü ve string birleştirme

# Ekrana Yazdırma
print("Müşteri Adı:", ad_buyuk_harf)
print("Müşteri ID:", customerID)

import math # Matematik işlemleri için Kütüphane
import datetime # Tarih işlemleri için

# 5 farklı müşterinin sözlük verisini içeren ana liste
###!!! Liste İçinde Sözlük Kullanımı !!!###
musteriler_listesi =  [
    {"ad_soyad": "Ali Yılmaz", "aylik_ucret": 300.0, "sadakat_ayi": 5, "aktif_mi": False},
    {"ad_soyad": "Ayşe Kaya", "aylik_ucret": 600.5, "sadakat_ayi": 30, "aktif_mi": True},
    {"ad_soyad": "Enes Demir", "aylik_ucret": 450.0, "sadakat_ayi": 2, "aktif_mi": True},
    {"ad_soyad": "Fatma Şahin", "aylik_ucret": 150.0, "sadakat_ayi": 12, "aktif_mi": False},
    {"ad_soyad": "Mehmet Çelik", "aylik_ucret": 550.0, "sadakat_ayi": 26, "aktif_mi": True}
]

# Fonksiyon Tanımlama
def tutar_hesapla(aylik_ucret): # Fonksiyon Tanımlama ve Parametre Alma
    kdvli_tutar = aylik_ucret * 1.20 # Matematiksel İşlem (%20 KDV ekleme)
    return kdvli_tutar # Fonksiyon Geri Dönüş Değeri (Return)

# Kütüphane Kullanımı ve For döngüsü
for musteri in musteriler_listesi:

    # Churn (Ayrılma) Riski Denetimi
    churn_riski = "Yok"
    if musteri["aktif_mi"] == False or musteri["sadakat_ayi"] < 6:
        churn_riski = "Yüksek (Müşteri Kaybedilebilir)"

    odenecek_tutar = tutar_hesapla(musteri["aylik_ucret"])         # Fonksiyon Çağırma
    yuvarlanmis_tutar = math.ceil(odenecek_tutar)                  # math.ceil ile yukarı yuvarlama
    bugunun_tarihi = datetime.datetime.now().strftime("%Y-%m-%d")  # Günün tarihini formatlama

    print(f"Müşteri: {musteri['ad_soyad']} | Risk Durumu: {churn_riski}")  # F-String
    print(f"Fatura Tutarı: {yuvarlanmis_tutar} TL")
    print(f"Tarih: {bugunun_tarihi}")
    print("-" * 30)                                                        # Ayırıcı Çizgi

#Hata Denetimi ve Set Kullanımı
tekrarli_hizmetler = ["Fiber İnternet", "IPTV", "Fiber İnternet", "Mobil Hat", "IPTV", "Akıllı Ev"]    # Tekrarlı Liste Kullanımı
benzersiz_hizmetler = set(tekrarli_hizmetler)                                                          # Set Kullanımı (Listedeki tekrarları silip benzersizleştirme)

print("Şirketin Sunduğu Benzersiz Hizmetler:")
for hizmet in benzersiz_hizmetler:                                                                      # Set Üzerinde Döngü Kullanımı
    print("- " + hizmet)